development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bhawkins2012@gmail.com
  :password: mxvwwzswxxiosujk
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bhawkins2012@gmail.com
  :password: mxvwwzswxxiosujk
  :enable_starttls_auto: true